### ISSUE TITLE
Incorrect old video.js dependency version

### ISSUE THREAD

**Issue by eigood** [videojs/videojs-contrib-media-sources#167]
In a project I've started, I installed video.js, which pulled in the latest version, 6.x.  I then added videojs-contrib-hls, which depends on video.js 5.x || 6.x.  This then depends on videojs-contrib-media-sources, which depends on video-js 5.x.  So now I have 2 copies of video.js in my webpack built bundle.

If you could update the video.js dep version to be done like videojs-contrib-hls, that would help tremendously, and reduce the size built bundle.

**Comment by gkatsev** [comment]
@eigood care to submit a PR that adds `|| 6.x` to the field in package.json?

**Comment by akofman** [comment]
Hello, 
Maybe I missed something but is it actually necessary to keep this dependency ? I mean, why don't you keep it as a devDependency and indicate it as external to Browserify ?

**Comment by gkatsev** [comment]
Because I've found that the peerDep system that previously was in npm to be unreliable at best and incredibly frustrating and broken at worst. Having it as a dependency isn't bad if the semver ranges inclusive enough as most bundlers, at least with the addition of `npm dedupe` (which happens automatically in newer npm etc) should take care of you not having multiple versions of video.js.

**Comment by eigood** [comment]
Sure, hang on.

**Comment by eigood** [comment]
Ping?

**Comment by gkatsev** [comment]
Oops, totally forgot. Thanks for your patience, we'll take a look today.
