### ISSUE TITLE
Improvement on videojs.MediaSource.supportsNativeMediaSources to handle cases better

### ISSUE THREAD

**Issue by muratakbal** [videojs/videojs-contrib-media-sources#58]
Apparently, implementation of `videojs.MediaSource.supportsNativeMediaSources` only checks if `MediaSource` is available in `window`. But, even if `window.MediaSource` is available, there's a chance that given mimeType is not supported by browser or disabled by user. As an example, Firefox doesn't support mp4 in some operating systems, but still supports media source. In that case, that logic'll choose `HtmlMediaSource` as media source and `nativeMediaSource.addSourceBuffer` will throw `NotSupportedError: Operation is not supported` because mp4 is not supported.

I don't know how hard it is, but somehow if you can check [isTypeSupported](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/isTypeSupported) in `videojs.MediaSource.supportsNativeMediaSources`, that would be more accurate.

@gkatsev wdyt?

**Comment by gkatsev** [comment]
That sounds right to me. @dmlap @imbcmdth?

**Comment by dmlap** [comment]
Yeah, makes sense to me too.

**Comment by GeyseR** [comment]
Hi, there.
We use Brightcove solution for delivering videos for our users. Recent version of Brightcove player based on videojs library and use this plugin as it's part. And we faced this error before and, unfotunately, after the fix above was merged (i checked that brightcove compiled script on our page has new code from PR) from . Error happens (only in FF, and only for small number of users) when script tries to execute `nativeMediaSource.addSourceBuffer('audio/mp4;codecs="' + this.codecs_[1] + '"')` statement. 
Probably we should check support not only for `'video/mp4;codecs="avc1.4d400d,mp4a.40.2"'` codecs, but for `'video/mp4;codecs="avc1.4d400d"'` and `'audio/mp4;codecs="mp4a.40.2"'`, too (see full fragment below).

Full fragment with adding source buffers:
```
var
        segment = event.data.segment,
        nativeMediaSource = this.mediaSource_.mediaSource_;

      // Cast ArrayBuffer to TypedArray
      segment.data = new Uint8Array(segment.data, event.data.byteOffset, event.data.byteLength);

      // If any sourceBuffers have not been created, do so now
      if (segment.type === 'video') {
        if (!this.videoBuffer_) {
          this.videoBuffer_ = nativeMediaSource.addSourceBuffer('video/mp4;codecs="' + this.codecs_[0] + '"');
        }
      } else if (segment.type === 'audio') {
        if (!this.audioBuffer_) {
          this.audioBuffer_ = nativeMediaSource.addSourceBuffer('audio/mp4;codecs="' + this.codecs_[1] + '"');
        }
      } else if (segment.type === 'combined') {
        if (!this.videoBuffer_) {
          this.videoBuffer_ = nativeMediaSource.addSourceBuffer('video/mp4;codecs="' + this.codecs_.join(',') + '"');
        }
      }
```
Fragment with getting codecs:
```
var
        buffer,
        codecs,
        avcCodec,
        mp4aCodec,
        avcRegEx = /avc1\.[\da-f]+/i,
        mp4aRegEx = /mp4a\.\d+.\d+/i;

      // create a virtual source buffer to transmux MPEG-2 transport
      // stream segments into fragmented MP4s
      if ((/^video\/mp2t/i).test(type)) {
        codecs = type.split(';').slice(1).join(';');
        codecs = translateLegacyCodecs(codecs);

        // Pull out each individual codec string if it exists
        avcCodec = (codecs.match(avcRegEx) || [])[0];
        mp4aCodec = (codecs.match(mp4aRegEx) || [])[0];

        // If a codec is unspecified, use the defaults
        if (!avcCodec || !avcCodec.length) {
          avcCodec = 'avc1.4d400d';
        }
        if (!mp4aCodec || !mp4aCodec.length) {
          mp4aCodec = 'mp4a.40.2';
        }
```
Sorry, i can't post direct link to full script source, because it can contain some secure data, may be you can touch Brightcove support for getting example source code.

**Comment by forbesjo** [comment]
@imbcmdth what are your thoughts on the above comment?
