### ISSUE TITLE
Avoid child-src: blob in CSP

### ISSUE THREAD

**Issue by sydneyli** [videojs/videojs-contrib-media-sources#97]
Using webworkify requires `child-src: "blob:"` in our CSP. We would prefer to keep a stricter CSP and not enable eval. Is it possible to bundle the webworker code into a separate JS file rather converting it into a data blob using webworkify? CC @devd, who pointed out the issue.

**Comment by gkatsev** [comment]
It's possible. The reason why we haven't done it yet and probably will never do it by default is because it requires the browser to do another request for the web worker file and making sure that that works properly across installs without just relying on loading that web worker file from a CDN is tricky.

**Comment by devd** [comment]
Makes sense. I was wondering if we could make it an optional setting.

**Comment by gkatsev** [comment]
It would probably need to be a custom build of media-sources because the CSP probably would complain that there is a blob in there even if it never ends up running.

**Comment by devd** [comment]
I think that's fine.. I would rather have that (warning in console but app
works fine) than the current solution and I am a big fan of not making this
a separate build.
